spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: never #using liquibase to initialize db

logging:
  level:
    liquibase: WARN

server:
  port: 8081
